### ISSUE TITLE
default path  'C:\Program Files\Unity\Hub\Editor\\Editor\Data\Managed\UnityEngine.dll',is error!

### ISSUE THREAD

**Issue by smallverse** [Rabadash8820/UnityAssemblies#12]
![企业微信截图_1652698328619](https://user-images.githubusercontent.com/11326721/168577677-3cc186af-4c72-451a-9be1-3ff830142b6f.png)

**Comment by Rabadash8820** [comment]
@smallverse That part of the path is supposed to include the Unity version number. Did you add a `<UnityVersion>` property to your project file as described in the Readme?

**Comment by Rabadash8820** [comment]
@smallverse Did adding `<UnityVersion>` resolve your issue?

**Comment by smallverse** [comment]
thanks
