### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by KannanKrish** [Rabadash8820/UnityAssemblies#14]
1) Automatic detection of Unit Engine location in my machine. If a user has multiple Unity versions it should pick the minimum version.
2) I want to access ECS functionality in my library.

**Comment by Rabadash8820** [comment]
Hi @KannanKrish!

1. I'm hesitant to do this, as it goes against NuGet's dependency model. In NuGet, a particular version of your project references a particular version of each dependency. The UnityEngine DLL is no different. By comparison, you wouldn't want your project to look up the minimum version of Json.NET or NUnit on your machine either; what if you were collaborating with someone whose machine had different versions? This package allows you either to reference the version of Unity used by a particular Unity project by setting `$(UnityProjectPath)` (which parses the project's `ProjectSettings/ProjectVersion.txt` file), or to reference a specific version of Unity by setting `$(UnityVersion)`. One of these approaches should fit your use case, but I'd be curious to hear why if not.
2. That's totally doable, you just need to reference the appropriate ECS assemblies. They should be present either under `$(UnityPackageCachePath)` or `$(UnityScriptAssembliesPath)` after you install the `Entities` UPM package in a Unity project.

**Comment by KannanKrish** [comment]
Thanks for the details explanation.

**Comment by Rabadash8820** [comment]
No problem. I'm gonna close this Issue. Feel free to reopen or open a new Issue if you have any other concerns.
