### ISSUE TITLE
readme.txt bug

### ISSUE THREAD

**Issue by drallcom3** [Rabadash8820/UnityAssemblies#16]
The readme.txt that opens automatically has some issues.
It proposes a Directory.Build.props that looks like this:
```
<Project>
        <UnityProjectPath>path\to\UnityProject</UnityProjectPath>
</Project
```
when in reality it has to look like this (the readme here on Git is correct):
```
<Project>
    <PropertyGroup>
        <UnityProjectPath>path\to\UnityProject</UnityProjectPath>
    </PropertyGroup>
</Project>
```

A > is missing and the PropertyGroup.
At first it didn't load for me, now it does.

**Comment by Rabadash8820** [comment]
Wo, nice catch! Just put out a [patch](https://www.nuget.org/packages/Unity3D/2.1.1) with the updated MSBuild snippet. Thanks for calling this out!

**Comment by yewnyx** [comment]
Following up on this one, Rider resolves the relative path not necessarily relative to `Directory.Build.props`, but from the saved location of `Unity3D.props`. As such, I needed to specify the UnityProjectPath in terms of the build project directory, i.e. `<UnityProjectPath>$(MSBuildProjectDirectory)\..\MyUnityProject</UnityProjectPath>`

**Comment by Rabadash8820** [comment]
Interesting. 🤔 I've never used Rider so thanks for bringing this to my attention. I'm not sure there's any good way to test if a project is building within Rider, so all I can probably do is add a warning to the Readme.

**Comment by Rabadash8820** [comment]
@yewnyx So actually I just ran into this same issue while setting up another project with this package and I see what you mean now. Just pushed out a [2.1.2 release](https://github.com/Rabadash8820/UnityAssemblies/releases/tag/v2.1.2) to update the example code in the package `readme.txt`. Thanks again for pointing this out!
