### ISSUE TITLE
System.IO.FileNotFoundException: 'Could not load file or assembly 'UnityEngine.CoreModule

### ISSUE THREAD

**Issue by ctownboy** [Rabadash8820/UnityAssemblies#18]
I'm using visual studio 2022 latest version, unity 6000.0.24,  .net 9.0, the project seems has located the assemblies successfully, but when I run the program with one line of code Debug.Log(), this Exception pops up.

**Comment by Rabadash8820** [comment]
@ctownboy Sorry to hear you're having trouble. 😕 I would need to see your project setup to troubleshoot further. Could you please do one of the following:
1. Link to a repo that replicates the issue
2. Attach a zip of a repo that replicates the issue to a comment here (excluding any files auto-generated by Unity or version control)

You can send the link or attachment in an email instead if you prefer.

Also, if you haven't already, you might try closing your VS solution, deleting the `.vs` folder and any `bin`/`obj` folders, then rebuilding.

**Comment by ctownboy** [comment]
[Test.zip](https://github.com/user-attachments/files/17942346/Test.zip)
Project files uploaded
@Rabadash8820

**Comment by Rabadash8820** [comment]
Thanks. Looks like you set `$(UnityInstallRootPath)` to the incorrect path. It should contain `Unity\Hub\Editor`, not `Unity Hub`. Alternatively, you could set `$(OSInstallRootPath)` to `D:\Project Files`, then this NuGet would use the correct relative directories. Just note that overriding these paths to hard-coded  Windows paths will prevent this project from building on MacOS/Linux dev machines.

**Comment by Rabadash8820** [comment]
@ctownboy I'm closing this Issue now. Feel free to re-open if my suggestion was not sufficient.
